apiVersion: v1
kind: BuildConfig
metadata:
  name: sample-pipeline
  labels:
    name: sample-pipeline
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsPipelineConfig:
        autoProvisionEnabled: false
      jenkinsfile: |-
        pipeline {
          agent {
            kubernetes {
              defaultContainer 'jnlp'
              yaml """
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            some-label: some-label-value
        spec:
          containers:
          - name: ansible
            image: kenmoini/jenkins-agent-ansible:latest
            command:
            - cat
            tty: true
            imagePullPolicy: Always
          - name: busybox
            image: busybox
            command:
            - cat
            tty: true
        """
            }
          }
          stages {
            stage('Run Ansible') {
              steps {
                container('ansible') {
                  sh 'cd /tmp && ansible --version'
                }
                container('busybox') {
                  sh '/bin/busybox'
                }
              }
            }
          }
        }